language: ruby
script: 'bundle exec rake spec'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby-19mode
  - jruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
